### ISSUE TITLE
Can't minify socket.io -service in angular

### ISSUE THREAD

**Issue by villesau** [btford/angular-socket-io-im#2]
Hi!

I have an issue with socket.io-service. When it is minificated, it does not work. i'm using SailsJS top of node.

And can you declare where the arguments -variable comes from?

**Comment by btford** [comment]
1. see `ngmin`
2. [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions_and_function_scope/arguments)

**Comment by villesau** [comment]
Now, after few hours of doing something else than coding, i realized both my self :D But still thanks a lot! ngmin seems very interesting!
